export const meta = {
  name: 'fleet-step6b-build',
  description: 'Step 6 Part B build: snapshot replay, QB/injury/EPA signals, epa_blend, sells; seven builders on disjoint paths in the wip-6b worktree',
  phases: [
    { title: 'Build', detail: 'replay, signals-models, ingest, host-models, sell-worker, sell-money, trading-ui in parallel' },
  ],
}

const REPO = '/home/user/pf-6b'
const SCRATCH = '<SCRATCHPAD>'
const CONTRACT = `${SCRATCH}/shapes6b.txt`
const COMMON = `
Repository: ${REPO}. It is a git worktree (branch wip-6b) of the polymarket-fleet repo with its OWN venv at ${REPO}/.venv; work only inside ${REPO} (never touch /home/user/polymarket-fleet, which another workflow is using). Do NOT commit or push; the orchestrator does that.
Project: a multi-machine fleet for NFL prediction-market (Polymarket US) model search and paper/live trading. Host = FastAPI + psycopg + Jinja2 + Postgres (host/), worker package fleet/ is standard-library only (CI enforces it).
Python: ${REPO}/.venv/bin/python. Run tests from ${REPO}: .venv/bin/python -m pytest <files> -q -p no:cacheprovider -o addopts= . Postgres 16 at postgresql://postgres:postgres@127.0.0.1:5432/postgres (export FLEET_TEST_DATABASE_URL to it; if "connection refused": pg_ctlcluster 16 main start). Per-test databases are cloned from a migrated template keyed by the migrations' digest.
Run ONLY your own test files plus the existing test files that cover the modules you change; never the full suite (the integrator does that; the machine has 4 cores shared with other agents). Keep runs short.
Read first, completely: ${REPO}/HANDOFF.md section 2 (the owner's rules), the shared contract ${CONTRACT} (implement it exactly; field names are fixed), the spec sections named below, and every module you change.
Style: Python 3.11+, type hints, plain docstrings, modules under about 300 lines (put new code in new sibling modules instead of growing files that are already near or over 300 lines), no em-dashes anywhere (code, tests, docs, templates). fleet/ stays standard-library only. Determinism: seed every random draw from strings.
Data: no network to Polymarket, ESPN or NFL.com; nflverse release files on github.com ARE reachable. tests/fixtures/games_sample.csv (2016-2025) is the games data for tests.
Owner rules that bind this step: paper is the default; the host enforces limits (workers only request approval); every order, fill and snapshot is logged; kill means cancel open orders only; free data only; all thresholds adjustable in Settings.
Only touch the paths you own (listed below). Other agents are writing the other paths right now. If you need a change in a path you do not own, do not make it: describe it precisely in your final report under "NEEDS FROM OTHERS" and code against the contract as if it existed.
Write tests in NEW test files named in your brief (do not edit tests/conftest.py or tests/test_dashboard.py; import helpers from tests/conftest.py freely).
Final report (your last message): files created/changed (one line each), the pytest summary lines of your runs, deviations from the contract with reasons, NEEDS FROM OTHERS, and open questions.
`

const BUILDERS = [
  { key: 'replay', prompt: `You are the REPLAY builder of step 6 Part B: snapshot replay backtests (docs/ROBUSTNESS.md B1, contract section C). ${COMMON}
Spec to read: docs/ROBUSTNESS.md Part B B1 and Part A (the metrics object and stress tests you extend), docs/MODELS.md "Backtest".
You own: fleet/sim/backtest.py, fleet/sim/records.py, fleet/sim/fills.py, fleet/sim/metrics.py, fleet/sim/stress.py, fleet/sim/robust.py, fleet/sim/validate.py (only if needed), new fleet/sim/prices.py (load the prices file, decision-time lookup, the replay fill using fleet.sim.book.walk), fleet/worker/context.py, fleet/worker/config.py, fleet/worker/jobs.py, fleet/common/http.py (only if needed), fleet/worker/agent.py (only the minimal lines that refresh the prices cache for a backtest with price_source snapshots, following refresh_games), tests/fake_host.py (serve GET /api/v1/data/prices), new tests/test_replay.py and tests/test_replay_resume.py.
Build: price_source closing_line (unchanged numbers, byte for byte: existing tests must stay green) and snapshots exactly as contract section C: scored games, decision time, p_market from the decision-time devigged mids, fills on depth or the bar touch, fees, CLV = closing_price - entry with the right sign, sim platform refused unless allow_sim_prices, stress price changes on snapshots, metrics fields price_source/platform/n_unscored_no_prices, checkpoint and resume exact (store the per-game price facts in the season entry). Tests: replay scores only games with data (bars within 30 minutes of the decision time), CLV sign on a constructed rising and falling close, sim excluded unless allowed, depth walk vs touch fallback, resume from every checkpoint equals an uninterrupted run, closing_line results unchanged.` },
  { key: 'signals-models', prompt: `You are the SIGNALS-MODELS builder of step 6 Part B: the QB-change and injury features, the EPA inputs on the worker, elo_blend penalties and the new epa_blend family (docs/ROBUSTNESS.md B2, contract section B). ${COMMON}
Spec to read: docs/ROBUSTNESS.md Part B B2, docs/MODELS.md (Model interface, elo_blend, search, summaries).
You own: fleet/sim/data.py, fleet/models/** except fleet/models/newton.py (use it), fleet/sim/search.py and fleet/sim/train.py (only if a family-generic change is needed), docs/MODELS.md (add the signals and the epa_blend section), new tests/test_signals_features.py, tests/test_epa_blend.py, tests/test_elo_penalties.py.
Build: FIELDS gain "signals"; load_games attaches "team_stats" (strictly earlier games of each team, oldest first, at most 16) from the payload's top-level "team_game_stats" (also accept a games list without it: empty stats); features_of adds "signals" and "team_stats" with safe defaults; elo_blend qb_change_penalty and out_penalty_per_player applied identically in fit and predict, new search draws appended at the end so old seeds reproduce the same earlier params, PARAM_KEYS and defaults updated (defaults 0 so existing models predict exactly as before: test it); epa_blend per the contract (rolling off/def EPA diffs over the "window" param games shrunk by n/(n+shrink) toward the league mean computed only from games before the predicted game, the feature list, fit by newton.fit_logistic with L2, search space, the three-sentence summary naming the signals that carried the result, from_json/to_json round trip). Tests: features on constructed rows (QB change across a season boundary, unknown starter gives 0, injuries Out counts), elo_blend unchanged with zero penalties, epa_blend recovers known coefficients on synthetic data, epa_blend never leaks (the same property test as elo_blend: altering a future game's result or stats does not change an earlier prediction), a small epa_blend search on the fixture runs end to end through fleet.sim.search.` },
  { key: 'ingest', prompt: `You are the INGEST builder of step 6 Part B: host-side ingest of nflverse injuries and play-by-play, the per-game signals, the games feed additions and the prices feed (contract sections B and C). ${COMMON}
Spec to read: docs/ROBUSTNESS.md Part B, docs/PROTOCOL.md (the data endpoints), host/nflverse.py and host/data_refresh.py (the games ingest you mirror; stdlib csv + urllib, no pandas).
You own: host/migrations/0007_signals.sql (additive edits only), new host/ingest_injuries.py, new host/ingest_pbp.py (stream the CSV.gz with gzip + csv, aggregate to team-game rows; never hold a whole season of plays in memory), host/signals.py (fill in game_signals per the contract, including the leakage rule on date_modified), new host/games_feed.py (the games feed body with "signals" per game and the top-level "team_game_stats", and the combined ETag), host/nflverse.py (only to delegate to games_feed), host/data_refresh.py (refresh injuries and play-by-play every signals_refresh_hours, current season plus the previous one; a CLI-triggered full backfill), host/cli.py (commands ingest-injuries and ingest-pbp with --season, following ingest-games), new host/prices_feed.py and host/api/data.py (GET /api/v1/data/prices per the contract, worker auth, ETag/304), docs/PROTOCOL.md (the data endpoint changes), new tests/fixtures/injuries_sample.csv and tests/fixtures/pbp_sample.csv.gz (cut SMALL real slices from nflverse: fetch https://github.com/nflverse/nflverse-data/releases/download/injuries/injuries_2023.csv and https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2023.csv.gz, keep only the columns you use and a handful of games of weeks 1-3, well under 200 KB each, and record the source in the test docstring), new tests/test_ingest_signals.py and tests/test_prices_feed.py.
Build and test: injuries upsert idempotent; team_game_stats from the play-by-play fixture with hand-checked EPA per play for one team-game; game_signals per the contract (QB change from games.raw qb ids across a season boundary, Out counts, the date_modified leakage rule); the games feed carries signals and team_game_stats and its ETag changes when injuries or stats change; GET /api/v1/data/prices returns only confirmed markets, bars and depth inside [kickoff - 6 h, kickoff), excludes platform sim unless asked, ETag/304 works.` },
  { key: 'host-models', prompt: `You are the HOST-MODELS builder of step 6 Part B: backtest params for snapshot replay, storing snapshot metrics, the leaderboard snapshot column group, the Models and Jobs pages and the Settings keys (contract section C). ${COMMON}
Spec to read: docs/ROBUSTNESS.md Part B B1 and "Dashboard and docs", docs/DASHBOARD.md (Models, Jobs, Settings), docs/MODELS.md "Leaderboard".
You own: host/jobparams.py (backtest KEYS gain price_source; copied settings decision_minutes_before_kickoff, allow_sim_prices, price_platform from market_source, participation), host/models.py and a new host/snapshot_store.py (POST /api/v1/models/{id}/backtest with price_source snapshots stores models.snapshot_metrics on the whole lineage and never touches backtest_metrics or eligibility), host/api/models.py (worker side routing only if needed), host/leaderboard.py plus a new host/leaderboard_snapshot.py (snapshot column group, rank basis precedence paper > snapshot (>= 30 snapshot bets, shrunk CLV) > validation, rank_mode "snapshot", unranked reasons unchanged), host/api/dashboard_models.py, host/api/job_forms.py, host/templates/models.html, host/templates/_model_row.html, host/templates/model.html, host/templates/jobs.html, host/templates/job.html, host/templates/_metrics.html, host/settings_schema.py, host/settings_forms.py (it is over 300 lines: move new parsing into a new sibling module), host/templates/settings.html (allow_sim_prices, decision_minutes_before_kickoff, the two nflverse URLs, signals_refresh_hours with hints), docs/ROBUSTNESS.md (mark what Part B delivered and any deviation), docs/DASHBOARD.md (Models, Jobs, Settings sections), new tests/test_snapshot_board.py and tests/test_snapshot_params.py.
Rules: phone-first layout as the existing pages (no horizontal scroll at 390 px, tap targets >= 40 px), plain words next to numbers, existing markup kept where tests rely on it. Tests: job params validation and copying, the routing of a snapshot result to snapshot_metrics, the leaderboard order with the three rank bases and their boundaries (29 vs 30 snapshot bets), the Models page shows the snapshot group with CLV and its range, the backtest form offers price_source, Settings validators for the new keys.` },
  { key: 'sell-worker', prompt: `You are the SELL-WORKER builder of step 6 Part B: the worker's sell proposals and the host's approval path for sells (docs/TRADING.md "Selling (step 6 Part B)", contract section D). ${COMMON}
Spec to read: docs/TRADING.md (the trade tick, approval, and the selling section), the worker tick fleet/worker/trade.py, the approval host/trading/limits.py.
You own: new fleet/worker/sell.py (pure helpers: sell proposals and stale sells), fleet/worker/trade.py (call the sell helpers in the tick, client_request_id for sells, keep buys' ids unchanged; it is over 300 lines so put new logic in sell.py), host/api/trade.py (OrderRequestBody gains order_side: "buy" | "sell", default "buy"), host/trading/limits.py (dispatch to approve_sell when order_side is sell; _insert stores orders.side; keep every buy check exactly as is), new host/trading/sells.py (approve_sell with the checks and reason codes of the contract, under the same approval lock and idempotency on client_request_id), host/trading/state.py (markets gain bid_depth; open_orders gain side; positions passthrough from host.trading.positions.positions(conn, assignment_id) whose rows are {"market_id", "side", "size", "basis_cents", "avg_cost"}; merge host.signals.game_signals into the payload's game), new tests/test_sell_worker.py and tests/test_sell_approval.py.
Note: host/trading/positions.py (signed positions with avg_cost) is being rewritten by the sell-money builder to the contract shape; code against that shape. Tests: the worker proposes a sell when the bid overshoots the model by min_edge and not otherwise, size never exceeds position minus open sells, at most one open sell per market, stale sells; approval: every reason code (no_position, sell_exceeds_position, open_sell_exists, kill, lease, assignment, market, mode, stale_book, participation on bids, price band bid - 0.05), no reservation and no daily-loss check for sells, idempotent client_request_id, buys unchanged (the existing tests/test_limits.py and tests/test_trade_worker.py stay green).` },
  { key: 'sell-money', prompt: `You are the SELL-MONEY builder of step 6 Part B: the money side of sells: ledger, fills, positions, paper sell fills, settlement after partial sales, scores, kill and the live gateway (docs/TRADING.md "Selling (step 6 Part B)", contract section D). ${COMMON}
Spec to read: docs/TRADING.md completely (ledger conventions, executor and paper fills, settlement, kill), docs/LIVE.md (gateway), the modules you own.
You own: host/migrations/0008_sells.sql (additive edits only), host/trading/ledger.py (sell()), host/trading/orders.py (record_fill for sell orders: basis per the contract, fills.basis_cents always set, sell orders never touch a reservation), host/trading/positions.py (signed positions: size = buys - sells, basis_cents = sum(fills.basis_cents of buys) - sum(of sells), avg_cost = basis_cents / (size * 100); rows {"market_id", "side", "size", "basis_cents", "avg_cost"} plus the existing mark fields; a closed position disappears), host/pnl.py, host/exchange/paper.py (sell fills via fleet.sim.book.walk(side="sell") on bid_depth, resting sells, participation shared per level and per side with the b{level} fill id suffix), host/exchange/settle.py plus a new host/exchange/settle_sells.py (sell bets rows, pro rata buy rows with the rounding residual on the last row, ledger settle on the remaining basis, model_scores pnl including sells and n_bets counting buys), host/paper_gate.py and host/leaderboard.py ONLY if they read bets in a way sells break (prefer leaving them untouched; report it), host/exchange/executor.py and host/exchange/live_sync.py (side-aware where needed), host/exchange/adapters/polymarket_us.py (live default side_sell "SELL") and host/exchange/adapters/polymarket_us_live.py (send side_sell for sell orders), host/kill.py (only if sells are not already covered), docs/TRADING.md (update the selling section to what was built, ledger conventions table), new tests/test_sell_ledger.py, tests/test_sell_paper.py, tests/test_sell_settlement.py, tests/test_sell_kill_live.py.
Tests (TRADING.md list): sell maths by hand, ledger invariants (replay_problems empty) after partial and full sales, settlement after a partial sale with exact totals, paper sell fills (marketable and resting, shared participation with a buy on the same snapshot), kill cancels open sells, the live gateway sends side SELL for a sell (fake http), existing tests/test_ledger.py, test_settlement.py, test_paper_fills.py, test_kill_switch.py, test_live_gateway.py stay green.` },
  { key: 'trading-ui', prompt: `You are the TRADING-UI builder of step 6 Part B: the Trading page for sells and positions (docs/TRADING.md "Selling": sells shown with a sell chip and their realized P&L; positions show size, average cost, current bid and unrealized P&L). ${COMMON}
Spec to read: docs/DASHBOARD.md (Trading page section and the phone layout rules), docs/TRADING.md (dashboard additions and selling), host/templates/_trading.html, host/api/dashboard_trading.py, host/trading/views.py.
You own: host/templates/_trading.html, host/templates/trading.html, host/api/dashboard_trading.py (it is near 300 lines: put new view shaping in a new sibling module such as host/trading/views_positions.py), host/trading/views.py, host/static/style.css (only new rules for the sell chip and positions table; keep the WCAG token pairs), new tests/test_trading_sells_page.py.
Build: a "sell" chip on sell orders (open, recent) and sell fills, realized P&L on sell fills; a Positions table per assignment (market side, size, average cost, current bid, unrealized P&L at the bid, in dollars) built from host.trading.positions.positions (contract shape) and the latest snapshot bid; empty states in words. Phone layout: no horizontal scroll at 390 px, tap targets >= 40 px, money as $1,234.56. Tests render the page with constructed sell orders, fills and positions (insert rows directly, the 0008 columns exist) and assert the chip, the positions row values and the fragment refresh route.` },
]

phase('Build')
const reports = await parallel(BUILDERS.map(b => () =>
  agent(b.prompt, { label: `build:${b.key}`, phase: 'Build', effort: 'high' })
    .then(r => ({ key: b.key, report: r || '(no report)' }))
))
const ok = reports.filter(Boolean)
log(`${ok.length}/${BUILDERS.length} builders reported`)
return { reports: ok }
