export const meta = {
  name: 'fleet-step3-build',
  description: 'Step 3: nflverse data, elo_blend model, walk-forward backtester, model search and training jobs, leaderboard; build in parallel, integrate end to end, review, fix',
  phases: [
    { title: 'Build', detail: 'models+sim (worker), agent data plumbing, host ingest/API/leaderboard, docs' },
    { title: 'Integrate', detail: 'full suite, real model search through the agent, screenshots, sanity numbers' },
    { title: 'Review', detail: 'modelling leakage/maths, API+security, UI' },
    { title: 'Fix', detail: 'apply findings, rerun suite' },
  ],
}

const REPO = '/home/user/polymarket-fleet'
const SHOTS = '<SCRATCHPAD>/screenshots-step3'
const COMMON = `
Repository: ${REPO} (git; steps 1 and 2 committed and green with 185 tests; do NOT commit or push, the orchestrator does that).
Python: ${REPO}/.venv/bin/python. Run tests as ${REPO}/.venv/bin/python -m pytest <files> -q -p no:cacheprovider -o addopts= (run from ${REPO} as cwd). Postgres 16 at postgresql://postgres:postgres@127.0.0.1:5432/postgres (tests create per-test databases from a template; see tests/conftest.py).
Read first, completely: ${REPO}/docs/MODELS.md (the modelling and backtest spec), the "Step 3 additions" section at the end of ${REPO}/docs/PROTOCOL.md, and the parts of ${REPO}/docs/PROTOCOL.md / ${REPO}/docs/DASHBOARD.md you touch. Fixture: ${REPO}/tests/fixtures/games_sample.csv (real nflverse games 2016-2025, 2761 rows, same columns as the live file at https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv which this sandbox CAN download if you need the full history for a sanity check; never make a test depend on the network).
Style: Python 3.11+, type hints, modules under ~300 lines (split rather than grow), plain docstrings, no em-dashes anywhere. fleet/ must stay standard-library only.
Runner/job contract: a job function is run(params, checkpoint, emit, should_stop) -> result (see fleet/worker/jobs.py); the runner child merges job["context"] into params as params["_context"] before calling it (context = {"games_path": <json cache file of games rows>, "model": <model dict or null>}); jobs emit(checkpoint, progress) after every unit of work (< 3 s) and raise JobStopped when should_stop() is true.
Only touch the paths you own; other agents are writing the other paths concurrently.
`

const MODELS_PROMPT = `You are building the MODELLING half of step 3: the first model family, the walk-forward backtester, model search and training, as pure standard-library Python that runs inside the worker's runner child. ${COMMON}

You own: ${REPO}/fleet/models/** (new), ${REPO}/fleet/sim/** (new), ${REPO}/fleet/worker/jobs.py (register the three kinds; keep sleep), ${REPO}/tests/test_models.py, ${REPO}/tests/test_backtest.py, ${REPO}/tests/test_search_train.py (all new). Do not touch fleet/worker/agent.py, fleet/worker/runner.py, fleet/common/*, host/, docs/, other tests.

Implement docs/MODELS.md exactly:
1. fleet/sim/odds.py: american_to_implied, devig(home_ml, away_ml) -> p_home_market (None when either is missing), logit/expit helpers; fleet/sim/data.py: load_games(path) from the JSON cache written by the agent (a list of dicts with the fields in MODELS.md; also accept the raw CSV columns so tests can load the fixture directly through a small csv adapter that computes kickoff order from gameday+gametime and normalises team codes OAK->LV, SD->LAC, STL->LA), sorted by kickoff then game_id, with season/week ints and scores ints or None.
2. fleet/models/base.py (Model interface as specified), fleet/models/registry.py (FAMILIES), fleet/models/elo_blend.py (Elo as specified: 1500 start, hfa, rest_adj with clamp, MOV multiplier formula, season regression; blend fitted by Newton's method on log-loss with L2 1e-3 on a and b, <= 25 iterations, tol 1e-8; fit(games, through, should_stop); predict(game, market_p, features); to_json/from_json; search_space(rng); summary(params, metrics) = exactly three sentences per the template). params_hash helper in fleet/models/base.py (sha256 of canonical JSON with sorted keys and floats rounded to 6 decimals, first 16 hex).
3. fleet/sim/fills.py: the closing-line fill rule and stake math exactly as in MODELS.md (fee_model, half_spread, min_edge, kelly_fraction, default_bankroll_cents, max_bet_cents, integer cents, ties return the stake). fleet/sim/metrics.py: all metrics listed (n_games, n_bets, total_stake_cents, pnl_cents, roi, hit_rate, avg_edge, avg_stake_cents, log_loss, brier, market_log_loss, calibration 10 buckets, max_drawdown_cents, max_drawdown, seasons) and per-season aggregation.
4. fleet/sim/backtest.py: run_backtest(games, family, params, seasons, limits, emit, should_stop, checkpoint) with one checkpoint unit per test season, resumable from a checkpoint (the per-season results so far), returning the metrics object plus per_season. Elo is replayed from the earliest game each fold (no stored state), the blend is fitted on seasons < S with at least 3 seasons of history, no refit inside the season, and the Elo update for a game happens only after its prediction is recorded. Skip betting and scoring for games without both moneylines; still update Elo.
5. fleet/sim/search.py: run_search(...) with candidate params from random.Random(f"{seed}:{i}"), unit = candidate x test season, checkpoint/result exactly as MODELS.md (top list ordered by shrunk ROI then log-loss; create_models entries with family, params, artifact null, backtest_metrics, summary, trained_through null). fleet/sim/train.py: run_train(...) for params.model_id with the parent model from params["_context"]["model"]: replay Elo through (season, week) inclusive, fit the blend on moneyline games before that point, return create_models with artifact and trained_through and parent_model_id, plus through and games_seen; unit = one season of replay.
6. fleet/worker/jobs.py: register "backtest", "model_search", "train" reading params["_context"] (games_path, model) and the limits from params (the host copies the relevant settings into params at job creation: fee_model, default_bankroll_cents, max_bet_cents, trade_max_games, backtest_seasons; fall back to the MODELS.md defaults when absent). A backtest with params.model_id uses the context model's family/params.
7. Tests (fixture-based, fast: keep the whole set under 60 s): odds conversion and devig; Elo update maths against hand-computed numbers (one game, one tie, MOV on/off, season regression, rest clamp); blend fit recovers known coefficients on synthetic data and is deterministic; NO LEAKAGE: predicting season S must not change when games from seasons >= S are altered or removed (property test over the fixture); backtest determinism (two runs identical) and resume equivalence (run to a checkpoint, stop via should_stop, resume: identical final metrics); fill rule and stake maths on hand-computed cases including the max_bet cap, the bankroll cap and a tie; metrics on a tiny synthetic season; drawdown definition; search: candidate i params reproducible from seed, resume equivalence, top ordering, create_models shape, summary is three sentences; train: artifact through point, child create_models shape, games_seen; per-unit timing: measure one candidate x one season on the fixture and assert < 1.5 s, and report the full-candidate time (2016-2025) in your final report.
Final report: files written, test summary lines (three runs), measured timings (one candidate full fixture backtest; one test season), the metrics of a 10-candidate search on the fixture (ROI, bets, log-loss vs market) so the orchestrator can sanity check them, and deviations.`

const AGENT_PROMPT = `You are building the WORKER-AGENT half of step 3: data cache, runner context, and model creation posts. ${COMMON}

You own: ${REPO}/fleet/worker/agent.py, ${REPO}/fleet/worker/runner.py, ${REPO}/fleet/common/http.py, ${REPO}/fleet/worker/config.py, ${REPO}/tests/fake_host.py, ${REPO}/tests/test_agent.py, ${REPO}/tests/test_runner.py. Do not touch fleet/models, fleet/sim, fleet/worker/jobs.py, host/, docs/, other tests. Another agent is writing fleet/models and fleet/sim and registering the three job kinds in fleet/worker/jobs.py; your tests must not depend on them (use the sleep kind plus a tiny test-only job injected through the fake host's job payload if you need a job that returns create_models: e.g. register an extra kind in the child only when env FLEET_TEST_JOBS=1, implemented inside tests, not in fleet/).

Implement the "Step 3 additions" of docs/PROTOCOL.md on the agent side:
1. fleet/common/http.py: get_json with If-None-Match support returning (status, body, etag) or a small response object; keep the existing API working.
2. Games cache: before starting a runner for kinds backtest, model_search or train, the agent refreshes <state>/cache/games.json from GET /api/v1/data/games using the stored ETag (<state>/cache/games.etag); on 304 keep the file; on network failure use the existing file if present (log a warning), else fail the job with a clear error. Fetch the model from GET /api/v1/models/{id} when params.model_id is set (failure -> fail the job). Build job["context"] = {"games_path": ..., "model": ...}. Runner.start passes context to the child; the child merges it into params as params["_context"] before calling the job function (do this in fleet/worker/runner.py run_child; keep the child protocol otherwise unchanged).
3. Results with create_models: when a runner finishes with result["create_models"], post each entry to POST /api/v1/models with job_id (in order), collect {"id", "lineage_id", "created"}, replace the list with result["created_models"], and for a backtest job with params.model_id post the metrics to POST /api/v1/models/{id}/backtest; only then queue the /complete post. These posts use the same persistent pending-post machinery (retry, survive restart) so a crash between posts does not lose a model: persist the partially completed post sequence in <state>/pending_posts.json with an index.
4. tests/fake_host.py: endpoints GET /api/v1/data/games (ETag/304, control setter set_games(rows)), GET /api/v1/models/{id}, POST /api/v1/models (idempotent on family+params_hash+trained_through, records calls, returns created flag, 409 when job_id is not leased by the caller), POST /api/v1/models/{id}/backtest; control helpers models(), model_posts().
5. tests/test_agent.py additions: cache is fetched before a backtest runner and the file exists with the rows; 304 keeps the cached file; network failure with a cached file proceeds with a warning, without a cached file fails the job (status failed with a clear error, no runner started); model fetched and present in the child's params["_context"] (use a test-only job that echoes params["_context"] keys into its result); create_models flow: result with two entries -> two POSTs in order -> /complete body carries created_models with ids; a crash after the first POST (simulate by killing the agent thread between posts using a fake host hook that blocks the second POST) resumes on the next start without duplicating the first model (idempotency plus persisted index); backtest job with model_id posts /backtest before /complete. tests/test_runner.py: the child merges context into params["_context"] and leaves params otherwise untouched.
Run your test files three times; all green. Final report: files written, summary lines, deviations, anything unfinished.`

const HOST_PROMPT = `You are building the HOST half of step 3: nflverse ingest, games/models tables and routes, job params validation, eligibility, leaderboard, dashboard models page and job forms. ${COMMON}

You own: ${REPO}/host/** (new migration 0003, new modules, templates, static), ${REPO}/tests/conftest.py (additions only), ${REPO}/tests/test_nflverse.py, ${REPO}/tests/test_models_api.py, ${REPO}/tests/test_eligibility.py (new), ${REPO}/tests/test_dashboard.py, ${REPO}/tests/test_owner_api.py, ${REPO}/tests/test_queue.py, ${REPO}/tests/test_cli.py, ${REPO}/docs/PROTOCOL.md and ${REPO}/docs/DASHBOARD.md (keep in sync, mark edits "(changed: reason)"). Do not touch fleet/, README.md, docs/DESIGN.md, docs/MODELS.md, tests/test_agent.py, tests/fake_host.py, tests/test_e2e.py, tests/hw/.

Build exactly what docs/PROTOCOL.md "Step 3 additions" and docs/MODELS.md describe:
1. Migration host/migrations/0003_models.sql: games (game_id text PK, season int, game_type text, week int, gameday date, gametime text null, kickoff_at timestamptz null, home_team, away_team, home_score int null, away_score int null, home_moneyline int null, away_moneyline int null, spread_line real null, total_line real null, home_rest int null, away_rest int null, div_game bool, roof text, surface text, temp int null, wind int null, status text (scheduled|final), raw jsonb, updated_at timestamptz); index (season, week), (kickoff_at). models (id uuid PK default gen_random_uuid(), lineage_id uuid not null, family text, params jsonb, params_hash text, artifact jsonb null, parent_model_id uuid null references models, trained_through jsonb null, summary text null, status text check (candidate, paper_ok, live_eligible, retired) default candidate, backtest_metrics jsonb null, created_by_job_id uuid null references jobs, created_at, updated_at; UNIQUE (family, params_hash, COALESCE(trained_through::text, '')) as a unique index; index (lineage_id)). Settings seeds: fee_model, thresholds_backtest, backtest_seasons, nflverse_refresh_hours, nflverse_url (https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv). Extend host/settings.py SCHEMA with validators for each (jsonb object shapes with ranges).
2. host/nflverse.py: fetch (urllib, 60 s timeout, size cap 50 MB) or read a local file; parse CSV; normalise team codes OAK->LV, SD->LAC, STL->LA; compute kickoff_at from gameday + gametime in America/New_York (gametime null -> 13:00 local); status final when both scores present; upsert into games (insert ... on conflict do update when raw differs; updated_at only when changed); returns counts. A host loop task refreshes every nflverse_refresh_hours and at startup when games is empty (never crash the loop on failure; log). CLI ingest-games [--file PATH]. Owner POST /api/data/refresh.
3. Worker routes (bearer): GET /api/v1/data/games with ETag/If-None-Match (ETag = count-maxupdated epoch), GET /api/v1/models/{id}, POST /api/v1/models (idempotent, lineage/status/metrics inheritance for children, job_id must be leased by the caller -> 409, params_hash computed server side with the same canonical rule as docs/MODELS.md), POST /api/v1/models/{id}/backtest. host/eligibility.py: recompute_lineage(conn, lineage_id) per MODELS.md; called on model creation and metrics update; status written to every row of the lineage.
4. Job params validation in create_job per kind (backtest/model_search/train/sleep): shapes and ranges from PROTOCOL.md; unknown keys rejected; model_id must exist (404 -> 400 "unknown model"); the host copies the relevant settings into params at creation (fee_model, default_bankroll_cents, max_bet_cents, trade_max_games, and backtest_seasons resolved with null -> last complete season from the games table) so the worker runs with the limits in force when the job was sent.
5. Owner API: GET /api/models (ranked and unranked lists per MODELS.md leaderboard rules), GET /api/models/{id}, POST /api/models/{id}/summary (<= 600 chars, audit), POST /api/models/{id}/status (retired only, audit; a retired lineage is excluded from ranking). Views in host/views.py or a new host/leaderboard.py.
6. Dashboard: enable the Models nav item; /models page (leaderboard table per DASHBOARD.md style: status badge, family, short params like "K 24 · HFA 55 · MOV on", ROI, bets, log-loss vs market, drawdown, seasons, the summary with an inline edit form, Train button opening the train form prefilled, Assign disabled "step 4"; unranked section; CC BY 4.0 attribution line for nflverse at the bottom), /models/{id} detail (params, metrics table overall and per season, calibration table, lineage members, creating job links, retire form). Jobs page: replace the single form with three forms (Backtest: model select or family+params JSON, seasons from/to; Model search: family, n, seed, seasons, top_k; Train: model select, through season/week) plus the sleep test form folded into a details element; keep any-idle/chosen target. Job detail renders backtest metrics and the search top list as tables and links to created models. Settings page: add groups for fee model, backtest thresholds, backtest seasons, nflverse refresh. Keep the phone layout rules (no horizontal scroll at 390 px, 44 px targets).
7. Tests: test_nflverse.py (parse the fixture: counts, normalisation, kickoff_at timezone conversion with a DST and a non-DST example, status, idempotent re-ingest changes nothing, changed row updates updated_at); test_models_api.py (create root -> lineage = id and status candidate; idempotent create; child inherits lineage/status/metrics; job_id not leased -> 409; backtest metrics update runs eligibility; GET games ETag 304; owner leaderboard ranking and unranked threshold; summary length limit; retire); test_eligibility.py (thresholds boundaries, demotion when metrics drop, lineage-wide status); test_queue.py (params validation per kind, settings copied into params, backtest_seasons null resolution); test_dashboard.py (models page renders ranked rows and the attribution, detail page, three job forms post valid jobs, invalid params re-render with an inline error, summary edit, phone layout assertions as before); test_cli.py (ingest-games --file fixture, models). Run only the tests you own plus tests/test_workers_api.py and tests/test_kill_switch.py.
Final report: files written, summary lines (three runs), deviations, anything unfinished.`

const DOCS_PROMPT = `You are writing docs for step 3 of a multi-machine fleet. ${COMMON}
You own: ${REPO}/README.md and ${REPO}/docs/DESIGN.md only.
1. README.md: add "How to test step 3" after the step 2 section: ingest games (docker compose exec host python -m host.cli ingest-games, or the Refresh button on Settings), send a model search from the Jobs page (family elo_blend, n 50, seed 1, seasons 2012 to last season) to any idle worker and watch the card flip to model_search and the progress climb; when it finishes, open Models: five candidates with three-sentence summaries, ROI, bets, log-loss vs market; click one, read the per-season table; press Train (through the current season and week) and see a child row appear in the same lineage; send a backtest for one model to a chosen box and read the metrics on the job detail page; move the worker's role mid-search and watch the job resume elsewhere repeating at most one candidate-season. Add an honest paragraph: backtests here use sportsbook closing lines (nflverse), so ROI near zero or slightly negative is normal and expected; they measure calibration and discipline, and the real test is paper trading on Polymarket prices in step 4, where closing line value is measured. Add the nflverse CC BY 4.0 attribution in a Data section. Update the Build order checklist (step 3 done). No em-dashes.
2. docs/DESIGN.md: update the "Models, backtester, scoring and leaderboard" section to reference docs/MODELS.md and the step 3 build-order row to done with the delivered scope; keep everything else.
Final report: files written and assumptions.`

const INTEGRATE_PROMPT = (reports) => `You are integrating step 3 of a multi-machine fleet after four agents built it in parallel (reports below). ${COMMON}
You own everything under ${REPO}. Keep docs/MODELS.md and docs/PROTOCOL.md as the spec; fix whichever side is wrong when they disagree and say so.
1. Full suite three times: ${REPO}/.venv/bin/python -m pytest ${REPO}/tests -q -p no:cacheprovider -o addopts=. Fix every failure in any file.
2. Extend tests/test_e2e.py (real uvicorn host + real agent + real runner) with a step 3 phase: ingest the fixture through the CLI or POST /api/data/refresh pointed at the fixture file (add a file path override if needed), send a model_search job (family elo_blend, n=3, seasons [2019, 2021], top_k 2) to any_idle -> worker flips to model_search, progress climbs, job succeeds, result.created_models has 2 ids, GET /api/models ranks or lists them, the Models page renders their summaries; send a train job for one of them (through 2021 week 10) -> child row in the same lineage with an artifact and trained_through; send a backtest for that model -> metrics on the job detail and on the model; preempt a running search (role to train mid-job) -> it resumes on the next model_search worker with at most one candidate-season repeated (compare evaluated counts). Keep the e2e under ~150 s.
3. Sanity run (not a test): with the full nflverse file downloaded to the scratchpad (https://github.com/nflverse/nflverse-data/releases/download/schedules/games.csv), run a 20-candidate search over seasons [2010, 2025] directly in Python (no host) and report the top-5 metrics: ROI, bets, hit rate, log-loss vs market log-loss, max drawdown, and the time per candidate. Sanity expectations: model log-loss within ~0.01 of the market's (the blend leans on the market), hit rate around 60-67% for favourites-heavy betting, ROI anywhere from -8% to +4%; anything wildly different (log-loss 0.5 or ROI +30%) means leakage or a maths bug: find and fix it, then rerun. Also report peak RSS of the runner child during a search (ps or /proc) to confirm it fits a 4 GB box.
4. Screenshots with ${REPO}/tests/hw/screenshots.py extended: /models, /models/{id}, /jobs (three forms), /jobs/{id} (search result with top list) at 390x844 and 1280x800, light and dark, saved to ${SHOTS}/; the same layout assertions as step 2 (no horizontal scroll at 390 px, 40 px targets in forms). Seed the database for the screenshots with real metrics from a short search on the fixture so the numbers look real.
5. compileall on fleet/ and host/; stdlib-only check on fleet/.
Final report: files changed (one line each), three pytest summary lines, the sanity-run table, peak RSS, PNG list, remaining known issues.
BUILD REPORTS:
${reports}`

const REVIEW_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: { type: 'object', properties: {
      severity: { type: 'string', enum: ['high', 'medium', 'low'] },
      file: { type: 'string' }, line: { type: 'integer' },
      summary: { type: 'string' }, failure_scenario: { type: 'string' }, suggested_fix: { type: 'string' },
      verified_by: { type: 'string' },
    }, required: ['severity', 'file', 'line', 'summary', 'failure_scenario', 'suggested_fix', 'verified_by'] } },
    overall: { type: 'string' },
  },
  required: ['findings', 'overall'],
}

const lenses = [
  { key: 'modelling', text: 'MODELLING CORRECTNESS AND LEAKAGE in fleet/models and fleet/sim against docs/MODELS.md: any path where information from a game or a later game reaches its own prediction (Elo updated before predict, blend fitted on the test season, season regression timing, kickoff ordering ties, rest days computed from future games, the through point in train being inclusive/exclusive consistently); the Elo and MOV formulas and the ratings regression; the Newton fit (convergence, regularisation, numerical safety at p near 0/1, deterministic); devig and American odds; the fill rule maths (cost, fee, edge, Kelly stake, caps, rounding, ties, payout in cents); metrics definitions (log-loss with ties as 0.5, Brier, calibration buckets, drawdown and its normalisation, ROI with zero bets); search determinism and resume equivalence; the shrunk-ROI objective; the three-sentence summary never lying (e.g. claiming an edge when ROI is negative). Write small scripts under <SCRATCHPAD>/review3-modelling/ and run them against the fixture to confirm each suspicion before reporting; include the numbers.' },
  { key: 'api', text: 'HOST API, QUEUE AND SECURITY for the new surface: POST /api/v1/models idempotency under concurrent posts (two workers posting the same candidate), lineage inheritance and status propagation, the job_id attribution check, params validation gaps (sizes, types, injection through params JSON shown on pages), settings copied into job params at creation, nflverse ingest robustness (malformed rows, missing columns, duplicate game ids, huge files, network failure in the loop thread, timezone and DST conversion of kickoff_at), ETag correctness (304 only when truly unchanged), eligibility recompute races, owner summary/status routes (XSS in summaries, length limits, audit), the agent side of create_models posting (crash between posts, duplicates, ordering), and the worker cache (stale games after a 304 when the ETag logic is wrong). Verify by running tests or scripts; report only confirmed problems.' },
  { key: 'ui', text: `UI AND PHONE USABILITY of the new Models and Jobs pages against docs/DASHBOARD.md and the owner's words "very simple and clean", "leaderboard with the three-sentence edge summary": look at every PNG under ${SHOTS}/ (Read them) and the templates/CSS: clutter, number formatting (percentages, cents as dollars, log-loss to 3 decimals), the summary readable on a phone, the three job forms not overwhelming (sensible defaults, the sleep test form tucked away), status badges consistent with the fleet page, disabled Assign clearly marked "step 4", attribution present, tap targets, no horizontal scroll, dark mode contrast. Report concrete template/CSS fixes.` },
]
const reviewPrompt = (lens, report) => `You are an adversarial reviewer of step 3 of a multi-machine fleet (models, backtester, search, train, leaderboard). ${COMMON}
Lens: ${lens.text}
Integration report:
${report}
Report only findings you verified; give a concrete failure scenario and a minimal fix each. Severity: high = leakage or maths error that misstates model quality, data loss, security hole; medium = wrong behaviour under realistic use or a clear usability failure; low = hygiene. Do NOT modify repository files.`

const fixPrompt = (findings) => `You are fixing verified review findings in step 3 of a multi-machine fleet. ${COMMON}
You own everything under ${REPO}. Apply every HIGH and MEDIUM finding (and cheap LOW ones), keep docs/MODELS.md, docs/PROTOCOL.md and docs/DASHBOARD.md in sync, add a regression test for each HIGH and MEDIUM. If a finding is wrong, say why and skip it. Then: full suite three times (${REPO}/.venv/bin/python -m pytest ${REPO}/tests -q -p no:cacheprovider -o addopts=), compileall on fleet/ and host/, stdlib-only check, and regenerate the screenshots with ${REPO}/.venv/bin/python ${REPO}/tests/hw/screenshots.py (output ${SHOTS}/) if any template/CSS/JS changed. If a modelling fix changes numbers, rerun the 20-candidate sanity search and report the new top-5 table.
Final report: per finding fixed/skipped(reason); files changed; three pytest summary lines; sanity table if rerun; whether screenshots were regenerated.
FINDINGS:
${JSON.stringify(findings, null, 1)}`

phase('Build')
log('Building models+sim, agent plumbing, host, docs in parallel')
const built = await parallel([
  () => agent(MODELS_PROMPT, { label: 'build:models', phase: 'Build', effort: 'high' }),
  () => agent(AGENT_PROMPT, { label: 'build:agent', phase: 'Build', effort: 'high' }),
  () => agent(HOST_PROMPT, { label: 'build:host', phase: 'Build', effort: 'high' }),
  () => agent(DOCS_PROMPT, { label: 'build:docs', phase: 'Build', model: 'sonnet', effort: 'medium' }),
])
const reports = built.map((r, i) => `=== ${['models', 'agent', 'host', 'docs'][i]} ===\n${r || '(no report)'}`).join('\n\n')

phase('Integrate')
const integrateReport = (await agent(INTEGRATE_PROMPT(reports), { label: 'integrate', phase: 'Integrate', effort: 'high' })) || '(no report)'

phase('Review')
const reviews = (await parallel(lenses.map(l => () =>
  agent(reviewPrompt(l, integrateReport), { label: `review:${l.key}`, phase: 'Review', schema: REVIEW_SCHEMA, model: 'opus', effort: 'high' })
))).filter(Boolean)
const findings = reviews.flatMap((r, i) => r.findings.map(f => ({ ...f, lens: lenses[i] ? lenses[i].key : 'unknown' })))
log(`${findings.length} findings (${findings.filter(f => f.severity !== 'low').length} high/medium)`)

phase('Fix')
let fixReport = '(no findings)'
if (findings.length > 0) {
  fixReport = (await agent(fixPrompt(findings), { label: 'fix', phase: 'Fix', effort: 'high' })) || '(no report)'
}
return { reports, integrateReport, reviews, fixReport }